# Project Charta
## Problem Definition
Formulate the context (domain/business area) and topic of the vizualation project. Which topical aspects should be adressed? Which question(s) should the data visualization project answer? What are the expected benefits of the project?   

### Stakeholder Analysis
List the people involved in and affected by the project. Describe their goals and relationships with each other. Visualisation in the form of a stakeholder map can provide a quick overview.

### User Analysis
Describe the problems and needs of the users of the product to be developed. What are the tasks that the users need to perform? What are their goals and motivations? What are their characteristics (e.g. demographics, technical skills, etc.)? Visualisation in the form of user personas can provide a quick overview.
Summary of the most important findings from the user analysis: relevant segments and user groups.  You can reference more detailed analyses such as individual "personas" or interviews in separate documents in the appendix.

Visualisierungsprodukt

Publikationsmedium
Wo soll das DataViz-Projekt publi-ziert werden, z.B. Website eines Unternehmens, einer Organisati-on oder App oder Intranet?

Zielgruppe(n)
Wer ist die Zielgruppe? 
Recherchiert Daten/Informationen zur Zielgruppe. Diese Recherche dient sp채ter f체r die Erstellung der 2 Personas.

Quellen:
Gebt die Quellen an, die ihr f체r euer DataViz-Projekt verwendet habt. Gebt auch an, welche Datenquellen ihr recherchiert habt und welche Datens채tze daraus ihr konkret verwendet habt.


## Situation Assessment
Describe the available resources (data, personnel, material, software/tools, infrastructure, etc.) and time as well as restrictions and constraints. Possible risks that may arise during the project are also identified.

## Project Objectives and Success Criteria
Describe the objectives **from the client/stakeholder perspective**. For example: "Enable users to understand the distribution of sales across different regions". Try to get information as specific as possible, but restrict to the concrete needs formulated by the client/stakeholders. For example: If a Dashboard is needed explicitly, then state it here, otherwise leave the form of the vizualization product open.

What are the success criteria (from the client/stakeholder perspective)? Formulate (qualitative) objectives, wherever possible, corresponding quantitative metrics and the target values to be achieved within the project.

It is also often helpful to specify what is explicitly excluded from the project objectives (out of scope).

## Visualization Goals
Map the project objectives to concrete visualization goals. For example:
* Composition form of the visiualization product - dashboard, data story, etc.
* Types of plots/visualizations to be used - e.g. bar chart, line chart, scatter plot, etc.
* Static vs. dynamic/interactive elements
* Embedding in the target environment - e.g. website, intranet, app, etc.
* Text and storytelling elements

Justify the proposal with the project objectives and specific user needs.


## Project Plan
Divide the project into individual phases, describe them briefly and draw up a preliminary timetable, e.g. as a Gantt chart:

See [Mermaid syntax for Gantt charts](https://mermaid.js.org/syntax/gantt.html). It might not be displayed correctly in Safari &#8594; use Chrome. [Live editor with export functionality](https://mermaid.live/)

```{mermaid}
%%| label: fig-project-plan
%%| fig-cap: Preliminary project plan in the form of a Gantt chart.
gantt
    title Project Plan
    dateFormat YYYY-MM-DD
    tickInterval 5day
    section Project Understanding
        Initiation workshop and problem definition     :a1, 2024-07-01, 1d
        Stakeholder and user analysis     :a3, 2024-07-02, 5d
        Situation assessment    :a4, 2024-07-06, 1d
        Project objectives and visualization goals    :a5, 2024-07-07, 1d
        Sign project charta: milestone, m1, 2024-07-08, 1d
    
    section Data Acquisition and Exploration
        Acquire data :a6, 2024-07-08, 3d
        Exploratory data analysis   :a7, 2024-07-09, 2d
        Discuss data report: milestone, m2, 2024-07-11, 1d
        
    section Visual Encoding and Design
        Overview charts   :a8, 2024-07-11, 3d
        Maps :a9, 2024-07-11, 5d
        Implement Dashboard prototype :a10, 2024-07-16, 5d
        Complete visualization report :a10, 2024-07-21, 1d
    section Evaluation
        Prepare presentation :a10, 2024-07-22, 2d
        Project presentation : milestone, m2, 2024-07-24, 4m
```

## Roles and Contact Details
List the people involved in the development work here with their role titles, tasks and contact details